### ISSUE TITLE
main route not connected

### ISSUE THREAD

**Issue by nachocarballeda** [LESSIoT/pivi-hardware#10]
There is name missmatch between +3.3VAC +3.3VCA labels.

**Comment by sebascerone** [comment]
I have the following labels in the board:
- +5V (main sheet)(regulator sheet)(connectors sheet)
- +3.3VADC (main sheet)(microcontroller sheet)(current measurement sheet)
- +3.3VDAC (connectors/CTx))
- +3.3VP (main sheet)(connectors sheet)
- +3V3 (microcontroller sheet)(regulator sheet)(voltage measurement sheet)
- +3.3VP (microcontroller sheet)
- GND

So, I guess I should change +3.3VCA labels to +3.3VAC labels, shouldn't I?

**Comment by sebascerone** [comment]
I fixed the sch, I will upload it in the next PR.
