### ISSUE TITLE
Female connector don't fit in the pcb

### ISSUE THREAD

**Issue by nachocarballeda** [LESSIoT/pivi-hardware#8]
It is needed to make two more cuts in the pcb for each female (audio jack 3.5mm) connector.
![bad_conn2](https://cloud.githubusercontent.com/assets/9441622/9646916/703b0dec-51ae-11e5-8c4a-75794d9bada1.jpg)

**Comment by sebascerone** [comment]
I do not understand the photo, could you explain it a little bit better?
